name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ddn_build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Hasura Project
      id: deploy-hasura
      uses: hasura/ddn-deployment@0.0.2
      with:
        hasura-pat: ${{ secrets.HASURA_PAT }}