name: Download and Install Hasura CLI

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download and Install Hasura CLI
      run: |
        curl -L https://graphql-engine-cdn.hasura.io/ddn/cli/v1/get.sh | bash

    - name: Run ddn build sm
      run: ddn version

    - name: Run login
      run: ddn login